<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Phonebook\Module'                        => __DIR__ . '/Module.php',
    'Phonebook\Controller\IndexController' => __DIR__ . '/src/Phonebook/Controller/IndexController.php',
    'PhonebookTest\Framework\TestCase'        => __DIR__ . '/tests/Phonebook/Framework/TestCase.php',
    'PhonebookTest\SampleTest'                => __DIR__ . '/tests/Phonebook/SampleTest.php',
);
