<?php
$title = 'Delete contact';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete contact
    <strong><?php echo $this->escapeHtml($this->contact->getFullname()); ?></strong>?
</p>
<form action="<?php echo $url = $this->url('phonebook/contact', array('action' => 'delete', 'id' => $this->contact->getId())); ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->contact->getId(); ?>" />
    <input type="submit" name="delete" value="Yes" class="btn btn-danger" />
    <input type="submit" name="delete" value="No" class="btn btn-success" />
</div>
</form>