<?php $contact = $this->contact; ?>
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title" id="contactModalLabel">Contact info</h4>
		</div>
		<div class="modal-body">
		<?php echo $this->partial('phonebook/partial/detail.phtml', array('contact' => $contact)); ?>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</div>
</div>